name: subpackage_lint_bootstrap
description: A bootstrap package for subpackage_lint
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  subpackage_lint:
    path: /Users/fre/Developer/Open Source/subpackage_lint/packages/subpackage_lint
