name: example
description: Example app for subpackage_lint
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.2

dev_dependencies:
  test:
  custom_lint: ^0.4.0
  subpackage_lint:
    path: ..
