analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_src_import_from_other_subpackage:
      exclude:
        - "*_test.dart"
        - "*.g.dart"
    - avoid_src_import_from_same_package:
      exclude:
        - "*_test.dart"
    - avoid_package_import_for_same_package:
      exclude:
        - "*_test.dart"
