name: subpackage_lint_test
description: tests for subpackage_lint package.
publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  subpackage_lint:
    path: ../subpackage_lint
    
dev_dependencies:
  test:
  

