name: subpackage_lint
description: A set of linting rules for clean code structure with subpackages.
version: 1.1.0+2
repository: https://github.com/dumazy/subpackage_lint

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  analyzer: ^5.12.0
  custom_lint_builder: ^0.5.0
  glob: ^2.1.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
